-- 코드를 작성해주세요
WITH FR AS(
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
PY AS(
    SELECT *
    FROM SKILLCODES
    WHERE NAME = 'Python'
),
CS AS(
    SELECT *
    FROM SKILLCODES
    WHERE NAME = 'C#'
)


SELECT CASE WHEN (D.SKILL_CODE & FR.CODE) != 0 AND (D.SKILL_CODE & PY.CODE) != 0 THEN 'A'
            WHEN (D.SKILL_CODE & CS.CODE) != 0 THEN 'B'
            WHEN (D.SKILL_CODE & FR.CODE) != 0 THEN 'C' END AS GRADE, D.ID, D.EMAIL
FROM FR, PY, CS, DEVELOPERS AS D
HAVING GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC

# HAVING 사용