-- 코드를 입력하세요
WITH RENTAL AS(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
)

SELECT DISTINCT A.CAR_ID, CASE WHEN R.CAR_ID IS NULL THEN '대여 가능' ELSE '대여중' END AS AVAILABILTY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A LEFT OUTER JOIN RENTAL AS R
ON A.CAR_ID = R.CAR_ID
ORDER BY A.CAR_ID DESC;