-- 코드를 작성해주세요
WITH CTE AS (
    SELECT A.FISH_TYPE AS TYPE, MAX(LENGTH) AS LEN, B.FISH_NAME AS NAME
    FROM FISH_INFO AS A, FISH_NAME_INFO AS B
    WHERE A.FISH_TYPE = B.FISH_TYPE
    GROUP BY A.FISH_TYPE
)

SELECT B.ID AS ID, NAME, LEN AS LENGTH
FROM CTE AS A, FISH_INFO AS B
WHERE A.TYPE = B.FISH_TYPE
AND B.LENGTH = LEN
ORDER BY ID ASC;