-- 코드를 작성해주세요
WITH AVG_SCORE AS (
    SELECT EMP_NO,
    CASE WHEN AVG(SCORE) >= 96 THEN 'S'
         WHEN AVG(SCORE) >= 90 THEN 'A'
         WHEN AVG(SCORE) >= 80 THEN 'B'
         ELSE 'C' END AS GRADE,
    CASE WHEN AVG(SCORE) >= 96 THEN 0.2
         WHEN AVG(SCORE) >= 90 THEN 0.15
         WHEN AVG(SCORE) >= 80 THEN 0.1
         ELSE 0 END AS RATE 
    FROM HR_GRADE
    GROUP BY YEAR, EMP_NO
)

SELECT AV.EMP_NO, E.EMP_NAME, AV.GRADE, E.SAL * AV.RATE AS BONUS
FROM AVG_SCORE AS AV, HR_EMPLOYEES AS E
WHERE AV.EMP_NO = E.EMP_NO


# bbbab